### PR TITLE
repo clean up

### PR DESCRIPTION
**Pull request by TomCC7**

### CODE REVIEW

**Comment by TomCC7** [comment]
Guys, I think I'm ready to merge all these changes into main branch. Most of the changes are structural changes and I also merged wizard code into this repo. I need your advices (especially from frontend team) on these changes to see if they are reasonable.

To summarize, the changes I made include
1. move old files that shouldn't be used into legacy folder
2. add [poetry](https://python-poetry.org/) for managing development environment
3. move backend and wizard folder into a umich_sim package

**Comment by jaeday** [comment]
Are there any metrics/testing that could be done to ensure that none of the original functionalities became buggy/faulty?

**Comment by TomCC7** [comment]
> Are there any metrics/testing that could be done to ensure that none of the original functionalities became buggy/faulty?

It's hard to do that... So I think you can mainly focus on structural change of the code base. And we'll fix all the potential bug eventually.

**Comment by jaeday** [comment]
I see, then I think it'd be nice to have if you could make a checklist of the features affected by this cleanup, have a non-scripted functionality tests (i.e just check that the frontend - backend link is still working fine) and add a note about it here, such that if the problems do arise in the future, people can fix them right away.

**Comment by TomCC7** [comment]
Well, there's no "link" between frontend and backend since they wrote a new backend last semester... And we are trying to figure out all the features we have right now :rofl:

**Review by magandren — APPROVED** [review]

**Pull request merged**
